# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
TARGETDIR = bin/debug
TARGET = $(TARGETDIR)/lrust
  define BUILDCMDS
	@echo Running build commands
	cd /home/game/open-source/game-server/ltask/3rd/lrust && cargo build
	cp -f /home/game/open-source/game-server/ltask/3rd/lrust/target/debug/librust.so /home/game/open-source/game-server/ltask/luaclib/rust.so
	# cp -rf /home/game/open-source/game-server/ltask/3rd/lrust/lualib/* /home/game/open-source/game-server/ltask/ext_lualib
  endef
  define CLEANCMDS
	@echo Running clean commands
	cd /home/game/open-source/game-server/ltask/3rd/lrust && cargo clean
  endef

else ifeq ($(config),release)
TARGETDIR = bin/release
TARGET = $(TARGETDIR)/lrust
  define BUILDCMDS
	@echo Running build commands
	cd /home/game/open-source/game-server/ltask/3rd/lrust && cargo build --release
	cp -f /home/game/open-source/game-server/ltask/3rd/lrust/target/release/librust.so /home/game/open-source/game-server/ltask/luaclib/rust.so
	# cp -rf /home/game/open-source/game-server/ltask/3rd/lrust/lualib/* /home/game/open-source/game-server/ltask/ext_lualib
  endef
  define CLEANCMDS
	@echo Running clean commands
	cd /home/game/open-source/game-server/ltask/3rd/lrust && cargo clean --release
  endef

else
  $(error "invalid configuration $(config)")
endif

$(TARGET):
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
