# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lrust_config = debug

else ifeq ($(config),release)
  lrust_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := lrust

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lrust:
ifneq (,$(lrust_config))
	@echo "==== Building lrust ($(lrust_config)) ===="
	@${MAKE} --no-print-directory -C . -f lrust.make config=$(lrust_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f lrust.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lrust"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"